require("__janus__.prototypes.item_groups")
require("__janus__.prototypes.items")
require("__janus__.prototypes.recipes")
require("__janus__.prototypes.time_distorter")
require("__janus__.prototypes.technologies")
